default-extensions:
- TypeApplications
- ImportQualifiedPost
- BlockArguments
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5

executables:
  Chapters:
    dependencies: sockets-and-pipes
    main: Main.hs
    source-dirs: Modules/Chapters
  ChaptersA:
    dependencies: sockets-and-pipes
    main: Main.hs
    source-dirs: Modules/ChaptersA

license: BSD3

name: nix-managed

version: 0.1.0.0
